[tool.black]
line-length = 110
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
  | migrations/*
  | .tmp
)/
'''

[tool.ruff]
line-length = 110
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.isort]
profile="black"
line_length=110
multi_line_output=3
known_django=["django"]
known_first_party=["config", "payhere"]
skip=["migrations"]
force_grid_wrap=0
include_trailing_comma=true
known_pandas=["pandas", "numpy"]
sections=["FUTURE","STDLIB","DJANGO","THIRDPARTY","PANDAS","FIRSTPARTY","LOCALFOLDER"]
use_parentheses=true
ensure_newline_before_comments=true
skip_glob = [
    "dist",
    "plugins",
    "docs",
    "scratches",
    "vfroot",
    "volumes",
    ".tmp",
    ".git",
    ".pants.d",
    ".pytest_cache",
    ".vscode",
]


[tool.mypy]
follow_imports="silent"
ignore_missing_imports=true

exclude='(?x)(^app\.py$ | ^__init__.py$)'
implicit_optional=true
namespace_packages=true
explicit_package_bases=true
allow_untyped_globals=true
allow_redefinition=true
disallow_untyped_defs=true

# Error output
show_column_numbers=true
show_error_context=true
show_error_codes=true
show_traceback=true
pretty=true
color_output=true
error_summary=true
plugins=[
    "mypy_django_plugin.main",
    "pydantic.mypy",
]

disable_error_code=[
    "operator",
    "misc"
]

[[tool.mypy.overrides]]
module="*.migrations.*"
ignore_errors=true

[[tool.mypy.overrides]]
module="manage"
ignore_errors=true

[[tool.mypy.overrides]]
module="*.tests.*"
ignore_errors=true

[tool.django-stubs]
django_settings_module="config.settings.base_mypy"

[tool.pydantic-mypy]
init_forbid_extra=true
init_typed=true
warn_required_dynamic_aliases=true
warn_untyped_fields=true

[tool.autoflake]
check = true
